app: pankkilinkki-app
service: pankkilinkki
useDotenv: true

plugins:
  - serverless-webpack
  - serverless-python-requirements

provider:
  name: aws
  region: eu-north-1
  stage: ${opt:stage, 'dev'}

  lambdaHashingVersion:
    20201221

    # Set the default RetentionInDays for a CloudWatch LogGroup
  logRetentionInDays: 365

  environment:
    # Stage defined with serverless command line flag.
    STAGE: ${opt:stage, 'dev'}
    SLACK_WEBHOOK_LOGS: ${env:SLACK_WEBHOOK_LOGS}
    SLACK_WEBHOOK_INFO: ${env:SLACK_WEBHOOK_INFO}

  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - sqs:GetQueueUrl
            - sqs:SendMessage
            - sqs:DeleteMessageBatch
          Resource:
            - Fn::GetAtt: [TaskQueue, Arn]
        - Effect: "Allow"
          Action:
            - s3:PutObject
            - s3:GetObject
            - s3:DeleteObject
          Resource:
            Fn::Join: ["", ["arn:aws:s3:::", "${self:custom.bucketName}", "/*"]]
        - Effect: "Allow"
          Action:
            - "s3:ListBucket"
          Resource: "arn:aws:s3:::*"

custom:
  queueName: pankkilinkki-${self:provider.stage}
  bucketName: pankkilinkki-${self:provider.stage}
  pythonRequirements:
    dockerizePip: true
    dockerImage: lambci/lambda:build-python3.8
    noDeploy:
      - futures
      - yapf
      - flake8
      - boto3

# Create resources with CloudFormation templates
resources:
  - ${file(resources/sqs-queue.yml)}

package:
  artifact: .serverless/pankkilinkki.zip

functions:
  handler:
    handler: handler.handler
    runtime: python3.8
    description: Pankkilinkki - handle downloaded files
    environment:
      ENDPOINT: ${env:ENDPOINT, 'http://localhost:8000'}
      API_KEY_B64: ${env:API_KEY_B64}
    events:
      - s3:
          bucket: ${self:custom.bucketName}
          event: s3:ObjectCreated:*
          rules:
            - prefix: files/

  linkki:
    handler: linkki.handler
    runtime: nodejs14.x
    description: Pankkilinkki - download files
    environment:
      BUCKET: ${self:custom.bucketName}
      QUEUE: ${self:custom.queueName}
      USERNAME: ${env:PANKKILINKKI_USERNAME}
      LANGUAGE: ${env:PANKKILINKKI_LANGUAGE, "FI"}
    events:
      - schedule:
          rate: rate(12 hours)
          enabled: true
          name: poll
      - schedule:
          rate: rate(30 days)
          enabled: true
          name: key-check
      - sqs:
          batchSize: 1
          arn:
            Fn::GetAtt: [TaskQueue, Arn]
